Better Makefile and add check-exe

diff --git a/update-visualredist/Makefile b/update-visualredist/Makefile
--- a/update-visualredist/Makefile
+++ b/update-visualredist/Makefile
@@ -86,9 +86,9 @@ IT_TEAM:=IT Support
 LOGDIR:=%WINDIR%\\Logs
 
 
-.PHONY: all checksum check-version clean control next ocs version wget
+.PHONY: all checksum check-version check-exe clean control next ocs version wget
 
-all: check-version $(SOFT)_$(VERSION)-$(REVISION)_x64.zip ocs
+all: check-version check-exe $(SOFT)_$(VERSION)-$(REVISION)_x64.zip ocs
 
 sinclude ../_common/conf.mk
 
@@ -101,10 +101,23 @@ clean:
 version: tmp/version-replace.txt
 	@sed -e 's#/# #g; s/__//g; s/^s/ */; s/[[:space:]]*;//;' tmp/version-replace.txt
 
-checksum:
-	@for pkg in $(VCREDIST); \
+checksum: $(VCREDIST)
+	@for exe in $(VCREDIST); \
 	do \
-		grep -q "^$$(shasum -a 256 $${pkg})$$" checksum.txt || echo "Error: bad checksum for binary $$(shasum -a 256 $${pkg})"; \
+		grep -q "^$$(shasum -a 256 $${exe})$$" ./checksum.txt || { shasum -a 256 "$(exe)"  >> ./checksum.txt ; }; \
+		ver=$$(peres -v $${exe} | grep "^Product Version:[[:space:]]" | awk '{print $$3}'); \
+		year=$$(dirname $${exe} | xargs -r basename); \
+		arch=$$(basename $${exe} | cut -f 2 -d '.'); \
+		grep -q "$${year}-.* $${ver}" ./version.txt || { echo " * $${year}-$${arch} $${ver}" >> ./version.txt; }; \
+	done
+	@if [ $$(( $$(date '+%s') - $$(stat -c '%Y' checksum.txt) )) -lt 60 ]; then tail -6 checksum.txt; fi
+	@if [ $$(( $$(date '+%s') - $$(stat -c '%Y' version.txt) )) -lt 60 ]; then tail -6 version.txt; fi
+
+check-exe: $(VCREDIST)
+	@for exe in $(VCREDIST); \
+	do \
+		file $${exe} | grep -q "PE32 executable" || { echo "Error: bad format for binary $${exe}" 1>&2 ; exit 1; } ; \
+		which peres >/dev/null && { grep -q $$(peres -v $${exe} | grep "^Product Version:[[:space:]]" | awk '{print $$3}') version.txt || { echo "Error: bad version for binary $${exe}" 1>&2 ; exit 1; } ; } ;\
 	done
 
 wget: $(VCREDIST)
